# This file is part of the Home Assistant role.
#
# Copyright (c) 2015-2017 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under MIT. All rights reserved.
#
---
- name: create user
  user: name={{ ha_user }} comment="Home Assistant" createhome=no system=yes shell="/sbin/nologin"

- name: create directory
  file: path={{ ha_conf_dir }} state=directory mode=02775 owner={{ ha_user }} group={{ ha_user }}

- name: create virtualenv directory
  file: path={{ ha_virtualenv_directory }} state=directory mode=02775 owner={{ ha_user }} group={{ ha_user }}
  when: ha_use_virtualenv

- name: install always-required packages
  package: name={{ item }} state=present
  with_items:
  - "{{ packages[ansible_distribution].always }}"

- name: install non-virtualenv packages
  package: name={{ item }} state=present
  with_items:
  - "{{ packages[ansible_distribution].nonvirtualenv }}"
  when: not ha_use_virtualenv

- name: install virtualenv packages
  package: name={{ item }} state=present
  with_items:
  - "{{ packages[ansible_distribution].virtualenv }}"
  when: ha_use_virtualenv

- name: install Debian-specific pip packages
  pip: name={{ item }} state=present executable=pip3
  with_items:
  - appdirs
  - packaging
  when:
  - ansible_distribution == "Debian"
  - not ha_use_virtualenv

- name: install Debian-specific pip packages
  pip: name={{ item }} state=present  virtualenv={{ ha_virtualenv_directory }} virtualenv_python=python3
  with_items:
  - appdirs
  - packaging
  when:
  - ansible_distribution == "Debian"
  - ha_use_virtualenv
  become: true
  become_user: "{{ ha_user }}"
